In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("lstm_data.csv")
#data = pd.read_csv("lstm_paper1_30_days_data.csv")
data = data.drop(['week','Unnamed: 0'],axis=1)
data = data['region4']
data

0       1
1       1
2       0
3       1
4       0
       ..
2622    0
2623    0
2624    0
2625    0
2626    0
Name: region4, Length: 2627, dtype: int64

In [30]:
data = data
data = np.array(data)
data

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [31]:
data = data[::-1]
data

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
num1 = 0
num2=0
for i in range(0,len(data)):
    if data[i] == 1:
        num1 = num1+1
    else:
        num2=num2+1
    

zero = len(data)/num2
one = len(data)/num1
zero

1.6970284237726099

In [35]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [36]:
n_steps = 50
X, y = splitSequence(data, n_steps)

In [37]:
X = np.expand_dims(X, 2)
X.shape

(2577, 50, 1)

In [38]:
print(X.shape,y.shape)

(2577, 50, 1) (2577,)


In [39]:
print(X,y)

[[[1]
  [1]
  [0]
  ...
  [1]
  [0]
  [0]]

 [[1]
  [0]
  [1]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [1]
  [0]
  ...
  [0]
  [0]
  [1]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]] [0 1 1 ... 0 0 0]


In [40]:
print(X[0])

[[1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]]


In [41]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [64]:
mod_lstm_r1 = tf.keras.Sequential()
#mod_lstm_r1.add(layers.LSTM(128))
mod_lstm_r1.add(layers.Dense(1))
mod_lstm_r1.add(layers.Dropout(0.2))
mod_lstm_r1.add(layers.Dense(256))
mod_lstm_r1.add(layers.Dense(64))
mod_lstm_r1.add(layers.Dense(1,activation='softmax'))

In [65]:
mod_lstm_r1.layers


In [66]:
mod_lstm_r1.compile(loss=tf.keras.losses.BinaryCrossentropy(),optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), metrics=['accuracy'])


In [67]:
X = X.astype('float32')
print(X.dtype)


float32


In [68]:
cw = {0:zero, 1:one}

In [69]:
mod_lstm_r1.fit(X, y, epochs=50,shuffle=False, class_weight=cw)


Epoch 1/50
81/81 [==============================] - 3s 11ms/step - loss: 15.3041 - accuracy: 0.4086
Epoch 2/50
81/81 [==============================] - 1s 13ms/step - loss: 15.3041 - accuracy: 0.4086
Epoch 3/50
81/81 [==============================] - 1s 13ms/step - loss: 15.3041 - accuracy: 0.4086
Epoch 4/50
81/81 [==============================] - 1s 12ms/step - loss: 15.3041 - accuracy: 0.4086
Epoch 5/50
81/81 [==============================] - 1s 12ms/step - loss: 15.3041 - accuracy: 0.4086
Epoch 6/50
81/81 [==============================] - 1s 14ms/step - loss: 15.3041 - accuracy: 0.4086
Epoch 7/50
41/81 [==============>...............] - ETA: 0s - loss: 12.3277 - accuracy: 0.5236

KeyboardInterrupt: 

In [ ]:
p = X[-50:]


In [ ]:
mod_lstm_r1.predict(p,verbose=0)

In [ ]:
y[-50:]

In [4]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [5]:
n_steps = 12
X, y = splitSequence(data, n_steps)

In [6]:
X.shape

(2615, 12)

In [7]:
print(X.shape,y.shape)

(2615, 12) (2615,)


In [8]:
len(X[:-20])

2595

In [9]:
xtrain, xtest, ytrain, ytest = X[:-20],X[-20:],y[:-20],y[-20:]

In [10]:
#n_features = 1
print(X.shape)

(2615, 12)


In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [20]:
mod1 = tf.keras.Sequential()
mod1.add(layers.LSTM(128,input_shape=(12,1)))
mod1.add(layers.Dropout(0.2))
mod1.add(layers.Dense(256))
mod1.add(layers.Dense(64))
mod1.add(layers.Dense(1,activation='softmax'))

In [21]:
mod1.layers


In [22]:
mod1.compile(loss=tf.keras.losses.BinaryCrossentropy(),optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), metrics=['accuracy'])


In [23]:
mod1.fit(xtrain, ytrain, epochs=50)


Epoch 1/50


ValueError: in user code:

    C:\Users\Charmi Shah\anaconda3\lib\site-packages\keras\engine\training.py:853 train_function  *
        return step_function(self, iterator)
    C:\Users\Charmi Shah\anaconda3\lib\site-packages\keras\engine\training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Charmi Shah\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Charmi Shah\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Charmi Shah\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Charmi Shah\anaconda3\lib\site-packages\keras\engine\training.py:835 run_step  **
        outputs = model.train_step(data)
    C:\Users\Charmi Shah\anaconda3\lib\site-packages\keras\engine\training.py:787 train_step
        y_pred = self(x, training=True)
    C:\Users\Charmi Shah\anaconda3\lib\site-packages\keras\engine\base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\Charmi Shah\anaconda3\lib\site-packages\keras\engine\input_spec.py:214 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_2 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 12)
