In [1]:
import pandas as pd
import numpy as np
#data = pd.read_csv("lstm_data.csv")
data = pd.read_csv("lstm_data.csv")

data = data.drop(['week','Unnamed: 0'],axis=1)
#data = data['region1']
data

region1  region2  region3  region4
0           0        0        0        1
1           0        0        0        1
2           1        0        0        0
3           0        0        1        1
4           0        0        0        0
...       ...      ...      ...      ...
2622        0        0        0        0
2623        0        0        0        0
2624        0        0        0        0
2625        0        0        0        0
2626        0        0        0        0

[2627 rows x 4 columns]

In [2]:
data = data
data = np.array(data)
data

array([[0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       ...,
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [3]:
data = data[::-1]
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       ...,
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=int64)

In [4]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [5]:
n_steps = 12
X, y = splitSequence(data, n_steps)

In [6]:
X.shape

(2615, 12, 4)

In [7]:
print(X.shape,y.shape)

(2615, 12, 4) (2615, 4)


In [8]:
len(X[:-20])

2595

In [9]:
xtrain, xtest, ytrain, ytest = X[:-20],X[-20:],y[:-20],y[-20:]

In [10]:
xtrain = xtrain.astype('float32')
print(xtrain.dtype)
xtest = xtest.astype('float32')
print(xtest.dtype)
ytrain = ytrain.astype('float32')
print(ytrain.dtype)
ytest = ytest.astype('float32')
print(ytest.dtype)

float32
float32
float32
float32


In [11]:
#n_features = 1
print(X.shape)

(2615, 12, 4)


In [12]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [31]:
mod1 = tf.keras.Sequential()
mod1.add(layers.LSTM(128,input_shape=(12,4)))
mod1.add(layers.Dropout(0.2))
mod1.add(layers.Dense(256))
mod1.add(layers.Dense(64))
mod1.add(layers.Dense(4,activation='softmax'))

In [32]:
## CNN combined with LSTM Model 
#i = (1000, 12)
model = tf.keras.Sequential ()
##1st model
model.add(layers.Conv1D(123, 3))
model.add(layers.MaxPooling1D(2))
model.add(layers.LSTM(256,  return_sequences=True))
model.add(layers.LSTM(64))
model.add(layers.Dense(240))
model.add(layers.Dense(120))
model.add(layers.Dense(60))
model.add(layers.Dense(30))
model.add(layers.Dense(4,activation="softmax"))


In [46]:
import tensorflow as tf
from tensorflow import keras
from keras import optimizers
opt=keras.optimizers.RMSprop(learning_rate=0.01)
import datetime

#from keras.optimizers import RMSprop
#opt = optimizers.RMSprop(lr=.005)

#model.compile(loss="mae",
#              optimizer=opt, #metrics=['mean_absolute_error'],
#              metrics=['accuracy'])

model.compile(loss=tf.keras.losses.BinaryCrossentropy(),optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), metrics=['accuracy'])

batch_size = 128 # mini-batch with 32 examples
epochs = 25
now = datetime.datetime.now

t=now()
history = model.fit(xtrain, ytrain,epochs=epochs,verbose=1)
print('Training time: %s' % (now() - t))

Epoch 1/25
82/82 [==============================] - 4s 20ms/step - loss: 0.4456 - accuracy: 0.2570
Epoch 2/25
82/82 [==============================] - 2s 19ms/step - loss: 0.4410 - accuracy: 0.2574
Epoch 3/25
82/82 [==============================] - 2s 19ms/step - loss: 0.4419 - accuracy: 0.2574
Epoch 4/25
82/82 [==============================] - 2s 19ms/step - loss: 0.4404 - accuracy: 0.2566
Epoch 5/25
82/82 [==============================] - 2s 19ms/step - loss: 0.4413 - accuracy: 0.2566
Epoch 6/25
82/82 [==============================] - 2s 19ms/step - loss: 0.4408 - accuracy: 0.2574
Epoch 7/25
82/82 [==============================] - 2s 18ms/step - loss: 0.4410 - accuracy: 0.2547
Epoch 8/25
82/82 [==============================] - 2s 19ms/step - loss: 0.4445 - accuracy: 0.2578
Epoch 9/25
82/82 [==============================] - 2s 18ms/step - loss: 0.4401 - accuracy: 0.2574
Epoch 10/25
82/82 [==============================] - 2s 19ms/step - loss: 0.4407 - accuracy: 0.2574
Epoch 11/

In [47]:
mod1.layers


In [48]:
mod1.compile(loss=tf.keras.losses.BinaryCrossentropy(),optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), metrics=['accuracy'])


In [49]:
X = X.astype('float32')
print(X.dtype)


float32


In [50]:
mod1.fit(xtrain, ytrain, epochs=25)


Epoch 1/25
82/82 [==============================] - 2s 10ms/step - loss: 0.4144 - accuracy: 0.2694
Epoch 2/25
82/82 [==============================] - 1s 11ms/step - loss: 0.4107 - accuracy: 0.2717
Epoch 3/25
82/82 [==============================] - 1s 11ms/step - loss: 0.4066 - accuracy: 0.2674
Epoch 4/25
82/82 [==============================] - 1s 11ms/step - loss: 0.4068 - accuracy: 0.2705
Epoch 5/25
82/82 [==============================] - 1s 11ms/step - loss: 0.4017 - accuracy: 0.2817
Epoch 6/25
82/82 [==============================] - 1s 12ms/step - loss: 0.3974 - accuracy: 0.2798
Epoch 7/25
82/82 [==============================] - 1s 11ms/step - loss: 0.3962 - accuracy: 0.2813
Epoch 8/25
82/82 [==============================] - 1s 11ms/step - loss: 0.3914 - accuracy: 0.2821
Epoch 9/25
82/82 [==============================] - 1s 12ms/step - loss: 0.3904 - accuracy: 0.2813
Epoch 10/25
82/82 [==============================] - 1s 11ms/step - loss: 0.3816 - accuracy: 0.2898
Epoch 11/

In [51]:
p = X[-20:]



In [52]:
ypred = mod1.predict(xtest)

In [53]:
yprednew = model.predict(xtest)

In [54]:
yprednew = (yprednew>0.3)
yprednew

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [55]:
ypred = (ypred>0.3)
ypred

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False,  True, False, False],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False,  True,  True, False],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [56]:
ytest

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

In [57]:
results = model.evaluate(xtest, ytest)
print("test loss, test acc:", results)

1/1 [==============================] - 1s 1s/step - loss: 0.4467 - accuracy: 0.4500
test loss, test acc: [0.4466701149940491, 0.44999998807907104]


In [58]:
results = mod1.evaluate(xtest, ytest)
print("test loss, test acc:", results)

1/1 [==============================] - 1s 674ms/step - loss: 0.5330 - accuracy: 0.4000
test loss, test acc: [0.5330023169517517, 0.4000000059604645]


In [59]:
print(p.shape)

(20, 12, 4)
