In [1]:
import pandas as pd
import numpy as np
#data = pd.read_csv("lstm_data.csv")
data = pd.read_csv("lstm_paper1_30_days_data.csv")

data = data.drop(['week','Unnamed: 0'],axis=1)
#data = data['region1']
data

region1  region2  region3  region4  region5  region6  region7  region8  \
0          0        0        0        0        0        0        0        0   
1          0        0        0        0        0        0        0        0   
2          0        0        0        0        0        0        0        0   
3          0        0        0        0        0        0        0        0   
4          0        0        0        0        0        0        0        0   
..       ...      ...      ...      ...      ...      ...      ...      ...   
606        0        0        0        0        0        0        0        0   
607        0        0        0        0        0        0        0        0   
608        0        0        0        0        0        0        0        0   
609        0        0        0        0        0        0        0        0   
610        0        0        0        0        0        0        0        0   

     region9  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
606        0  
607        0  
608        0  
609        0  
610        0  

[611 rows x 9 columns]

In [2]:
data = data
data = np.array(data)
data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [3]:
data = data[::-1]
data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [4]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [5]:
n_steps = 12
X, y = splitSequence(data, n_steps)

In [6]:
X.shape

(599, 12, 9)

In [7]:
print(X.shape,y.shape)

(599, 12, 9) (599, 9)


In [8]:
print(X[0],y[0])

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]] [0 0 0 0 0 0 0 0 0]


In [9]:
n_features = 1
print(X.shape)

(599, 12, 9)


In [10]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [11]:
mod1 = tf.keras.Sequential()
mod1.add(layers.LSTM(128,input_shape=(12,9)))
mod1.add(layers.Dropout(0.2))
mod1.add(layers.Dense(256))
mod1.add(layers.Dense(64))
mod1.add(layers.Dense(9))

In [12]:
mod1.layers


In [13]:
mod1.compile(loss=tf.keras.losses.CategoricalCrossentropy(),optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), metrics=['accuracy'])


In [14]:
X = X.astype('float32')
print(X.dtype)


float32


In [15]:
mod1.fit(X, y, epochs=50)


Epoch 1/50
19/19 [==============================] - 2s 11ms/step - loss: nan - accuracy: 0.8731
Epoch 2/50
19/19 [==============================] - 0s 9ms/step - loss: nan - accuracy: 0.9165
Epoch 3/50
19/19 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.9165: 0s - loss: nan - accuracy: 0.9
Epoch 4/50
19/19 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.9165
Epoch 5/50
19/19 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.9165
Epoch 6/50
19/19 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.9165
Epoch 7/50
19/19 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.9165
Epoch 8/50
19/19 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.9165
Epoch 9/50
19/19 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.9165
Epoch 10/50
19/19 [==============================] - 0s 10ms/step - loss: nan - accuracy: 0.9165
Epoch 11

KeyboardInterrupt: 

In [16]:
p = X[-2:]


In [17]:
mod1.predict(p)

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan]], dtype=float32)

In [67]:
print(p.shape)

(2, 12, 9)


In [65]:
s = np.array([])
np.insert(s,p)

TypeError: _insert_dispatcher() missing 1 required positional argument: 'values'