In [46]:
import pandas as pd
import numpy as np
#data = pd.read_csv("lstm_data.csv")
data = pd.read_csv("lstm_data.csv")

data = data.drop(['week','Unnamed: 0'],axis=1)
#data = data['region1']
data

region1  region2  region3  region4
0           0        0        0        1
1           0        0        0        1
2           1        0        0        0
3           0        0        1        1
4           0        0        0        0
...       ...      ...      ...      ...
2622        0        0        0        0
2623        0        0        0        0
2624        0        0        0        0
2625        0        0        0        0
2626        0        0        0        0

[2627 rows x 4 columns]

In [47]:
data = data
data = np.array(data)
data

array([[0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       ...,
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [48]:
data = data[::-1]
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       ...,
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=int64)

In [49]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [50]:
n_steps = 12
X, y = splitSequence(data, n_steps)

In [51]:
X.shape

(2615, 12, 4)

In [53]:
print(X.shape,y.shape)

(2615, 12, 4) (2615, 4)


In [54]:
len(X[:-20])

2595

In [55]:
xtrain, xtest, ytrain, ytest = X[:-20],X[-20:],y[:-20],y[-20:]

In [56]:
xtest = xtest.astype('float32')
print(xtest.dtype)

float32


In [57]:
#n_features = 1
print(X.shape)

(2615, 12, 4)


In [58]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [109]:
mod1 = tf.keras.Sequential()
mod1.add(layers.SimpleRNN(64,return_sequences = False))
#mod1.add(layers.RNN(128,return_sequences = True))
#mod1.add(layers.SimpleRNN(128,return_sequences = True))

#mod1.add(layers.LSTM(128,return_sequences = True))
#mod1.add(layers.Dropout(0.2))
mod1.add(layers.Dense(256))
mod1.add(layers.Dense(64))
mod1.add(layers.Dense(4,activation='softmax'))

In [110]:
mod1.layers


In [111]:
mod1.compile(loss=tf.keras.losses.BinaryCrossentropy(),optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), metrics=['accuracy'])


In [93]:
xtrain = xtrain.astype('float32')
print(xtrain.dtype)
xtest = xtest.astype('float32')
print(xtest.dtype)

float32
float32


In [94]:
ytrain = ytrain.astype('float32')
print(ytrain.dtype)
ytest = ytest.astype('float32')
print(ytest.dtype)

float32
float32


In [44]:
"""
xtrain = np.asarray(xtrain).astype('float32').reshape((-1,1))
xtest = np.asarray(xtest).astype('float32').reshape((-1,1))
ytrain = np.asarray(ytrain).astype('float32').reshape((-1,1))
ytest = np.asarray(ytest).astype('float32').reshape((-1,1))
"""

In [112]:
mod1.fit(xtrain, ytrain, epochs=50)


Epoch 1/50
82/82 [==============================] - 2s 7ms/step - loss: 1.0726 - accuracy: 0.2416
Epoch 2/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4822 - accuracy: 0.2459
Epoch 3/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4889 - accuracy: 0.2470
Epoch 4/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4877 - accuracy: 0.2543
Epoch 5/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4733 - accuracy: 0.2455
Epoch 6/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4631 - accuracy: 0.2520
Epoch 7/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4518 - accuracy: 0.2586
Epoch 8/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4527 - accuracy: 0.2570
Epoch 9/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4458 - accuracy: 0.2505
Epoch 10/50
82/82 [==============================] - 1s 8ms/step - loss: 0.4569 - accuracy: 0.2570
Epoch 11/50
82/82 [

In [115]:
yprednew = mod1.predict(xtest)

In [116]:
yprednew = (yprednew>0.3)
yprednew

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False, False,  True]])

In [117]:
ytest

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

In [118]:
results = mod1.evaluate(xtest, ytest)
print("test loss, test acc:", results)

1/1 [==============================] - 1s 925ms/step - loss: 0.5712 - accuracy: 0.3500
test loss, test acc: [0.5711668133735657, 0.3499999940395355]
