In [1]:
import pandas as pd
import numpy as np
#data = pd.read_csv("lstm_data.csv")
data = pd.read_csv("lstm_data.csv")

data = data.drop(['week','Unnamed: 0'],axis=1)
#data = data['region1']
data

region1  region2  region3  region4
0           0        0        0        1
1           0        0        0        1
2           1        0        0        0
3           0        0        1        1
4           0        0        0        0
...       ...      ...      ...      ...
2622        0        0        0        0
2623        0        0        0        0
2624        0        0        0        0
2625        0        0        0        0
2626        0        0        0        0

[2627 rows x 4 columns]

In [3]:
data = data
data = np.array(data)
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       ...,
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=int64)

In [4]:
data = data[::-1]
data

array([[0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       ...,
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [5]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [6]:
n_steps = 12
X, y = splitSequence(data, n_steps)

In [7]:
X.shape

(2615, 12, 4)

In [8]:
print(X.shape,y.shape)

(2615, 12, 4) (2615, 4)


In [9]:
len(X[:-20])

2595

In [10]:
xtrain, xtest, ytrain, ytest = X[:-20],X[-20:],y[:-20],y[-20:]

In [11]:
xtest = xtest.astype('float32')
print(xtest.dtype)

float32


In [12]:
#n_features = 1
print(X.shape)

(2615, 12, 4)


In [25]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [26]:
mod3 = tf.keras.Sequential()
mod3.add(layers.SimpleRNN(64,return_sequences = False))
#mod3.add(layers.RNN(128,return_sequences = True))
#mod3.add(layers.SimpleRNN(128,return_sequences = True))

#mod3.add(layers.LSTM(128,return_sequences = True))
#mod3.add(layers.Dropout(0.2))
mod3.add(layers.Dense(256))
mod3.add(layers.Dense(64))
mod3.add(layers.Dense(4,activation='softmax'))

In [27]:
mod3.layers


In [28]:
mod3.compile(loss=tf.keras.losses.BinaryCrossentropy(),optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), metrics=['accuracy'])


In [29]:
xtrain = xtrain.astype('float32')
print(xtrain.dtype)
xtest = xtest.astype('float32')
print(xtest.dtype)

float32
float32


In [30]:
ytrain = ytrain.astype('float32')
print(ytrain.dtype)
ytest = ytest.astype('float32')
print(ytest.dtype)

float32
float32


In [31]:
"""
xtrain = np.asarray(xtrain).astype('float32').reshape((-1,1))
xtest = np.asarray(xtest).astype('float32').reshape((-1,1))
ytrain = np.asarray(ytrain).astype('float32').reshape((-1,1))
ytest = np.asarray(ytest).astype('float32').reshape((-1,1))
"""

"\nxtrain = np.asarray(xtrain).astype('float32').reshape((-1,1))\nxtest = np.asarray(xtest).astype('float32').reshape((-1,1))\nytrain = np.asarray(ytrain).astype('float32').reshape((-1,1))\nytest = np.asarray(ytest).astype('float32').reshape((-1,1))\n"

In [32]:
mod3.fit(xtrain, ytrain, epochs=25)


Epoch 1/25
82/82 [==============================] - 1s 3ms/step - loss: 1.5229 - accuracy: 0.2474
Epoch 2/25
82/82 [==============================] - 0s 3ms/step - loss: 0.7013 - accuracy: 0.2563
Epoch 3/25
82/82 [==============================] - 0s 3ms/step - loss: 0.6560 - accuracy: 0.2497
Epoch 4/25
82/82 [==============================] - 0s 3ms/step - loss: 0.5575 - accuracy: 0.2655
Epoch 5/25
82/82 [==============================] - 0s 3ms/step - loss: 0.4888 - accuracy: 0.2605
Epoch 6/25
82/82 [==============================] - 0s 3ms/step - loss: 0.5709 - accuracy: 0.2443
Epoch 7/25
82/82 [==============================] - 0s 3ms/step - loss: 0.4803 - accuracy: 0.2466
Epoch 8/25
82/82 [==============================] - 0s 3ms/step - loss: 0.5095 - accuracy: 0.2663
Epoch 9/25
82/82 [==============================] - 0s 3ms/step - loss: 0.4852 - accuracy: 0.2513
Epoch 10/25
82/82 [==============================] - 0s 3ms/step - loss: 0.4669 - accuracy: 0.2551
Epoch 11/25
82/82 [

In [33]:
yprednew = mod3.predict(xtest)

In [34]:
yprednew = (yprednew>0.3)
yprednew

array([[False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False]])

In [35]:
ytest

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [38]:
results = mod3.evaluate(xtest, ytest)
print("test loss, test acc:", results)

1/1 [==============================] - 1s 674ms/step - loss: 0.3000 - accuracy: 0.510
test loss, test acc: [0.300023169517517, 0.5100000059604645]
